services:
  mcp-ipm:
    image: ghcr.io/neto-developer/mcp-ipm:latest
    build: .
    env_file: .env
    networks:
      - argonsolar-network

networks:
  argonsolar-network:
    external: true
    name: infra_argonsolar-network
