services:
  mcp-ipm:
    image: ghcr.io/neto-developer/mcp-ipm:latest
    build: .
    env_file: .env
    volumes:
      - mcp-data:/app/mcp-data
    networks:
      - argonsolar-network

volumes:
  mcp-data:

networks:
  argonsolar-network:
    external: true
    name: infra_argonsolar-network
